#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 11 19:17:29 2017

@author: xuyizhou
"""

filePath='/Users/xuyizhou/Desktop/after.txt'
fileRead = []
with open(filePath) as fileRaw:
    for line in fileRaw:
        fileRead.append(line)
data=int(flieRead)